import pandas as pd
import numpy as np
import os
import glob
from scipy.stats import entropy
import discretization_config as dc

# Input/Output
RAW_DATA_DIR = "sim_data/raw_batch"
RESULTS_FILE = "emergence_results.csv"


def discretize_dataset(df):
    """Maps continuous dataframe to discrete integers using Global Bins."""
    disc_df = pd.DataFrame()
    total_capacity_bits = 0

    for col, bins in dc.DISCRETE_BINS.items():
        if col not in df.columns:
            continue

        # Apply the calibrated bins
        disc_df[col] = pd.cut(df[col], bins=bins, labels=False, include_lowest=True)

        # Sum theoretical max capacity
        mi = dc.CAPACITIES[col]
        total_capacity_bits += np.log2(mi)

    return disc_df, total_capacity_bits


def calculate_shannon_entropy(series):
    """H(X) in bits."""
    if len(series) == 0: return 0
    probs = series.value_counts(normalize=True, sort=False)
    return entropy(probs, base=2)


def analyze_run(file_path):
    df = pd.read_csv(file_path)

    # 1. Discretize
    disc_df, theoretical_capacity = discretize_dataset(df)

    # 2. Construct Joint State
    # Combine all columns into a single tuple representation (s1, s2, s3...)
    disc_df['joint_state'] = disc_df.apply(tuple, axis=1)

    # 3. Calculate Joint Entropy H(S)
    h_joint = calculate_shannon_entropy(disc_df['joint_state'])

    # 4. Calculate Emergence (Generalized Sum Rule Simplification)
    # V(N) = Capacity - H(Joint)
    # This represents the "Constraints" generated by the system.
    # (Note: For the full recursive independence subtraction, you would iterate subsets here.
    # For Type 2 proof, demonstrating V(N) > 0 vs Baseline is often sufficient,
    # but strictly V(N) = Sum(log M) - H(Joint) is the global constraint).

    emergence = theoretical_capacity - h_joint

    # Extract run info
    filename = os.path.basename(file_path)
    strategy = filename.split('_')[1]  # e.g. run_static_01 -> static

    return {
        "Run": filename,
        "Strategy": strategy,
        "Theoretical_Capacity": theoretical_capacity,
        "Observed_Entropy": h_joint,
        "Emergence_Score": emergence
    }


def main():
    print("--- Calculating Strong Emergence (Type 2) ---")

    all_files = glob.glob(os.path.join(RAW_DATA_DIR, "*.csv"))
    results = []

    for f in all_files:
        res = analyze_run(f)
        results.append(res)

    # Save Results
    res_df = pd.DataFrame(results)
    res_df.to_csv(RESULTS_FILE, index=False)

    # Print Summary Statistics
    print("\nSummary Results (Mean Emergence per Strategy):")
    print(res_df.groupby("Strategy")["Emergence_Score"].agg(["mean", "std"]))
    print(f"\nDetailed results saved to {RESULTS_FILE}")


if __name__ == "__main__":
    main()