import pandas as pd
import numpy as np
import os
import glob

# --- THEORETICAL CAPACITIES (M) ---
CAPACITIES = {
    "num_iiots": 3,  # Low, Med, High
    "bus_flow": 3,  # Constrained, Nominal, Turbo
    "edge_flow": 3,
    "scada_flow": 3,
    "queue_len": 4,  # Log-spaced bins
    "success_rate": 3
}

RAW_DATA_DIR = "sim_data/raw_batch"


def format_bins_for_export(bins_list):
    """
    Helper to ensure the config file is valid Python code.
    Converts numpy scalars to native floats and replaces 'inf' with 'np.inf'.
    """
    # 1. Convert all values to native Python floats to remove 'np.float64(...)' wrappers
    clean_list = [float(x) for x in bins_list]

    # 2. Convert to string representation
    list_str = str(clean_list)

    # 3. Replace raw 'inf' with 'np.inf' so the import works
    # This automatically handles '-inf' -> '-np.inf' as well
    list_str = list_str.replace("inf", "np.inf")

    return list_str


def get_log_bins(data_series, n_bins):
    """Generates Logarithmic Bin Edges."""
    clean_data = data_series[data_series >= 0]
    if len(clean_data) == 0: return [0, 1, 10, 100]  # Fallback

    start = clean_data.min()
    end = clean_data.max()
    shift = 1.0  # Handle 0

    bins = np.logspace(np.log10(start + shift), np.log10(end + shift), n_bins + 1)
    bins = bins - shift
    bins[0] = -np.inf
    bins[-1] = np.inf
    return list(bins)


def get_quantile_bins(data_series, n_bins):
    """Generates bin edges based on equal-frequency quantiles."""
    try:
        _, bins = pd.qcut(data_series, n_bins, retbins=True, duplicates='drop')
        bins = list(bins)
        bins[0] = -np.inf
        bins[-1] = np.inf
        return bins
    except ValueError:
        return [-np.inf] + list(np.linspace(data_series.min(), data_series.max(), n_bins - 1)) + [np.inf]
    except Exception:
        return [-np.inf, np.inf]  # Emergency fallback


def main():
    print("--- Calibrating Phase Space from Global Data ---")

    all_files = glob.glob(os.path.join(RAW_DATA_DIR, "*.csv"))
    if not all_files:
        print("No data found! Run generate_emergence_batch.py first.")
        return

    df_list = []
    for f in all_files:
        try:
            df_list.append(pd.read_csv(f))
        except pd.errors.EmptyDataError:
            print(f"Skipping empty file: {f}")

    if not df_list:
        print("Data files found but empty.")
        return

    full_df = pd.concat(df_list, ignore_index=True)
    print(f"Loaded {len(full_df)} total state vectors.")

    calibrated_bins = {}

    # A. Queue (Logarithmic)
    if "queue_len" in full_df.columns:
        print("Calibrating Queue (Logarithmic)...")
        calibrated_bins["queue_len"] = get_log_bins(full_df["queue_len"], CAPACITIES["queue_len"])

    # B. Others (Quantiles)
    for col, m in CAPACITIES.items():
        if col == "queue_len": continue
        if col in full_df.columns:
            print(f"Calibrating {col} (M={m})...")
            calibrated_bins[col] = get_quantile_bins(full_df[col], m)

    # C. Write Config File
    with open("discretization_config.py", "w") as f:
        f.write("# AUTOMATICALLY GENERATED BY calibrate_bins.py\n")
        f.write("import numpy as np\n\n")

        f.write("CAPACITIES = {\n")
        for k, v in CAPACITIES.items():
            f.write(f'    "{k}": {v},\n')
        f.write("}\n\n")

        f.write("DISCRETE_BINS = {\n")
        for k, bins in calibrated_bins.items():
            # USE THE NEW FORMATTING HELPER HERE
            formatted_bins = format_bins_for_export(bins)
            f.write(f'    "{k}": {formatted_bins},\n')
        f.write("}\n")

    print("--- Calibration Complete. 'discretization_config.py' updated (Syntax Fixed). ---")


if __name__ == "__main__":
    main()