# AUTOMATICALLY GENERATED BY calibrate_bins.py
import numpy as np

CAPACITIES = {
    "num_iiots": 12,
    "bus_flow": 12,
    "edge_flow": 12,
    "scada_flow": 12,
    "queue_len": 12,
    "success_rate": 12,
}

DISCRETE_BINS = {
    "num_iiots": [-np.inf, np.float64(0.4), np.float64(1.4), np.float64(2.5), np.float64(3.6), np.float64(5.5), np.float64(8.5), np.float64(13.7), np.float64(24.0), np.float64(45.9), np.float64(87.1), np.float64(165.7), np.inf],
    "bus_flow": [-np.inf, np.float64(18.3), np.float64(60.9), np.float64(119.5), np.float64(190.9), np.float64(274.6), np.float64(366.2), np.float64(427.2), np.float64(452.8), np.float64(474.6), np.float64(496.5), np.float64(521.5), np.inf],
    "edge_flow": [-np.inf, np.float64(18.9), np.float64(63.4), np.float64(125.7), np.float64(173.7), np.float64(197.9), np.float64(220.7), np.float64(242.0), np.float64(263.1), np.float64(284.4), np.float64(304.0), np.float64(323.9), np.inf],
    "scada_flow": [-np.inf, np.float64(11.8), np.float64(31.6), np.float64(49.8), np.float64(66.3), np.float64(80.2), np.float64(92.5), np.float64(104.5), np.float64(116.4), np.float64(128.4), np.float64(140.9), np.float64(156.6), np.inf],
    "queue_len": [-np.inf, np.float64(0.5), np.float64(3.5), np.float64(13.0), np.float64(31.3), np.float64(63.0), np.float64(110.4), np.float64(175.5), np.float64(263.9), np.float64(385.2), np.float64(693.1), np.float64(1555.0), np.inf],
    "success_rate": [-np.inf, np.float64(0.4), np.float64(1.4), np.float64(2.6), np.float64(4.6), np.float64(8.3), np.float64(14.3), np.float64(23.5), np.float64(39.6), np.float64(74.9), np.float64(169.0), np.float64(363.9), np.inf],
}


